// Generated by CoffeeScript 1.7.0
(function() {
  var Inventory, InventoryDialog, InventoryWindow, ItemPile, ModalDialog,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Inventory = require('inventory');

  InventoryWindow = require('inventory-window');

  ItemPile = require('itempile');

  ModalDialog = require('voxel-modal-dialog');

  module.exports = function(game, opts) {
    return new InventoryDialog(game, opts);
  };

  module.exports.pluginInfo = {
    'loadAfter': ['voxel-recipes', 'voxel-carry', 'voxel-registry']
  };

  module.exports.InventoryDialog = InventoryDialog = (function(_super) {
    __extends(InventoryDialog, _super);

    function InventoryDialog(game, opts) {
      var contents, element, _i, _len, _ref, _ref1, _ref2, _ref3;
      this.game = game;
      if (!this.game.isClient) {
        return;
      }
      this.registry = (function() {
        var _ref1;
        if ((_ref = (_ref1 = game.plugins) != null ? _ref1.get('voxel-registry') : void 0) != null) {
          return _ref;
        } else {
          throw new Error('voxel-inventory-dialog requires "voxel-registry" plugin');
        }
      })();
      this.playerInventory = (function() {
        var _ref2, _ref3, _ref4;
        if ((_ref1 = (_ref2 = (_ref3 = game.plugins) != null ? (_ref4 = _ref3.get('voxel-carry')) != null ? _ref4.inventory : void 0 : void 0) != null ? _ref2 : opts.playerInventory) != null) {
          return _ref1;
        } else {
          throw new Error('voxel-inventory-dialog requires "voxel-carry" plugin or playerInventory" set to inventory instance');
        }
      })();
      this.playerIW = new InventoryWindow({
        inventory: this.playerInventory,
        registry: this.registry
      });
      this.upper = document.createElement('div');
      _ref3 = (_ref2 = opts.upper) != null ? _ref2 : [];
      for (_i = 0, _len = _ref3.length; _i < _len; _i++) {
        element = _ref3[_i];
        this.upper.appendChild(element);
      }
      contents = [];
      contents.push(this.upper);
      contents.push(document.createElement('br'));
      contents.push(this.playerIW.createContainer());
      InventoryDialog.__super__.constructor.call(this, game, {
        contents: contents,
        escapeKeys: [192, 69]
      });
    }

    InventoryDialog.prototype.enable = function() {};

    InventoryDialog.prototype.disable = function() {};

    return InventoryDialog;

  })(ModalDialog);

}).call(this);
